# Generated by Django 3.2.9 on 2021-12-19 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_identifyingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CreatedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
