# Generated by Django 3.2.9 on 2021-12-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herbs',
            fields=[
                ('Herb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Detail_page', models.CharField(max_length=256)),
                ('Picture_url', models.CharField(max_length=256)),
                ('Name', models.CharField(max_length=256)),
                ('Subname', models.CharField(max_length=256)),
                ('English_name', models.CharField(max_length=256)),
                ('Medical_part', models.CharField(max_length=256)),
                ('Plant_pose', models.CharField(max_length=256)),
                ('Produce_place', models.CharField(max_length=256)),
                ('Pick_reproduce', models.CharField(max_length=256)),
                ('Herb_info', models.CharField(max_length=256)),
                ('Taste', models.CharField(max_length=256)),
                ('Function', models.CharField(max_length=256)),
                ('Medical_function', models.CharField(max_length=256)),
                ('Medical_search', models.CharField(max_length=256)),
                ('Chemistry_component', models.CharField(max_length=256)),
                ('Taboo', models.CharField(max_length=256)),
            ],
        ),
    ]
