# Generated by Django 3.2.9 on 2021-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20211214_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_name', models.TextField(null=True)),
                ('Picture_url', models.TextField(null=True)),
                ('Book_tag', models.TextField(null=True)),
                ('Book_info', models.TextField(null=True)),
                ('Book_author', models.TextField(null=True)),
                ('Book_publishdate', models.DateField()),
                ('Book_publish', models.TextField(null=True)),
            ],
        ),
    ]
