# Generated by Django 3.2.9 on 2021-12-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_publishdate',
            field=models.TextField(null=True),
        ),
    ]
