# Generated by Django 3.2.9 on 2021-12-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_createdtime'),
        ('search', '0005_alter_books_book_publishdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.TextField(null=True)),
                ('Herb', models.ManyToManyField(to='search.Herbs')),
                ('User', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
