# Generated by Django 3.2.9 on 2021-12-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='id',
        ),
        migrations.AlterField(
            model_name='frequency',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
